### ISSUE TITLE
Set up initial file structure in rj-software repo

### ISSUE THREAD

**Issue by renawrli** [RoboJackets/robowrestling-software#1]
See: https://docs.google.com/document/d/1RbehZDdIJHKc1LXL25ZQ3ThyH5eDeag7ld0SLd391Po/edit

this easy pls do

**Comment by holyschick** [comment]
File structure:
- README.md
- simulator
- strategy
  - documentation
  - Strategy1.cpp
  - Strategy2.cpp
  - …

- robot1
  - lib
  - library files
  - READMEorDIE.md (& other documentation)

- robot1.ino
  - functionality.cpp/h
  - allowed_strategies.txt
